package com.mycompany.swingapplication.view;

import com.mycompany.swingapplication.controller.Controller;
import com.mycompany.swingapplication.model.Food;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Main view window.
 *
 * @author Sławomir Kowalczyk
 */
public class MainFrame extends JFrame {

    private Food food;
    private Controller controller;
    private DefaultListModel attributsList;
    private List<JButton> mainFrameButtons;

    /**
     * Creates a new main view.
     */
    public MainFrame() {
        this.food = new Food();
        this.controller = new Controller(this);
        this.attributsList = new DefaultListModel();

        initComponents();
        buttonsBuild();

        optionFrame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent event) {
                controller.setEditFood(null);
                setIdTF("");
                setNameTF("");
                setScientificNameTF("");
            }
        });
    }

    /**
     * Responsible for creating buttons. Each button represents one a food.
     */
    public void buttonsBuild() {
        mainFrameButtons = new LinkedList<>();
        for (int i = 0; i < food.getFoods().size(); i++) {
            String name = "<html>"
                    + food.getFoods().get(i).getId() + ". "
                    + food.getFoods().get(i).getName() + ",<br/>&nbsp;&nbsp;"
                    + food.getFoods().get(i).getScientificName()
                    + "</html>";
            String pathImage = "src/main/resources/images/" + food.getIconList().get(i) + ".png/";
            ImageIcon icon = new ImageIcon(pathImage);

            JButton button = new JButton(name, icon);

            button.setActionCommand(food.getFoods().get(i).toString());
            controller.putButtonFoodMap(button, food.getFoods().get(i));
            button.addActionListener(controller);
            mainFrameButtons.add(button);
            mainPanelWithFoods.add(button);
        }
    }

    /**
     * Removes the food list from the main panel.
     */
    public void removeAllFromPanelWithFoods() {
        mainPanelWithFoods.removeAll();
        mainPanelWithFoods.revalidate();
        mainPanelWithFoods.repaint();
    }

    /**
     * Removes selected food from the main panel.
     *
     * @param b Food to remove.
     */
    public void removeFromPanelWithFoods(JButton b) {
        mainPanelWithFoods.remove(b);
        mainPanelWithFoods.revalidate();
        mainPanelWithFoods.repaint();
    }

    /**
     * Adds selected food to the main panel.
     *
     * @param b Food to add.
     */
    public void addToPanelWithFoods(JButton b) {
        mainPanelWithFoods.add(b);
        mainPanelWithFoods.revalidate();
        mainPanelWithFoods.repaint();
    }

    /**
     * Sets the secound window paramters. Fills the list of tags.
     */
    public void showOptionWindow() {
        optionFrame.setSize(500, 430);
        optionFrame.setResizable(false);
        optionFrame.setLocationRelativeTo(null);
        optionFrame.setVisible(true);
        setAllTagsList();
    }

    /**
     * Fills the list of all tagges.
     */
    public void setAllTagsList() {
        for (int i = 0; i < food.getAllTagsList().size(); i++) {
            attributsList.addElement(food.getAllTagsList().get(i));
        }
        allTags.setModel(attributsList);
    }

    /**
     * Displays panel with a message for a user.
     *
     * @param message Message for a user.
     */
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Message", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Displays panel asking to confirm the operation.
     *
     * @param message Message for a user.
     * @return Returns selected answer as a number.
     */
    public int showMessageYesOrNo(String message) {
        return JOptionPane.showConfirmDialog(this, message, "Message", JOptionPane.YES_NO_OPTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionFrame = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        allTags = new javax.swing.JList<>();
        addTagToThisFood = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        scientificNameTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        foodTags = new javax.swing.JComboBox<>();
        deleteTagsB = new javax.swing.JButton();
        saveB = new javax.swing.JButton();
        addIcon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanelWithFoods = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        optionB = new javax.swing.JButton();
        deleteB = new javax.swing.JButton();
        editB = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        searchTF = new javax.swing.JTextField();
        searchB = new javax.swing.JButton();

        optionFrame.setTitle("Option");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tags panel"));

        jScrollPane2.setViewportView(allTags);

        addTagToThisFood.setText("Add tag to this food");
        addTagToThisFood.setToolTipText("");
        addTagToThisFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTagToThisFoodActionPerformed(evt);
            }
        });

        jLabel7.setText("Select tag");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addTagToThisFood))
                    .addComponent(jLabel7))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTagToThisFood))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit panel"));

        jLabel2.setText("Id:");

        jLabel3.setText("Name:");

        jLabel4.setText("Scientific name:");

        jLabel5.setText("Tags:");

        deleteTagsB.setText("Delete attribute");
        deleteTagsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTagsBActionPerformed(evt);
            }
        });

        saveB.setText("Save");
        saveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBActionPerformed(evt);
            }
        });

        addIcon.setText("Add icon");
        addIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(foodTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(scientificNameTF))
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteTagsB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(scientificNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(foodTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteTagsB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addIcon)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout optionFrameLayout = new javax.swing.GroupLayout(optionFrame.getContentPane());
        optionFrame.getContentPane().setLayout(optionFrameLayout);
        optionFrameLayout.setHorizontalGroup(
            optionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        optionFrameLayout.setVerticalGroup(
            optionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main window");
        setLocationByPlatform(true);

        mainPanelWithFoods.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainPanelWithFoods.setLayout(new java.awt.GridLayout(4, 4, 4, 3));
        jScrollPane1.setViewportView(mainPanelWithFoods);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("List of Foods");

        optionB.setText("Option");
        optionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionBActionPerformed(evt);
            }
        });

        deleteB.setText("Delete");
        deleteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBActionPerformed(evt);
            }
        });

        editB.setText("Edit");
        editB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBActionPerformed(evt);
            }
        });

        jLabel8.setText("Search by name");

        searchB.setText("Search");
        searchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(optionB, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(deleteB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addGap(30, 30, 30)
                                .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(searchB)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchB))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(editB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(optionB)
                        .addGap(0, 328, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBActionPerformed
        controller.delete();
    }//GEN-LAST:event_deleteBActionPerformed

    private void optionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionBActionPerformed
        showOptionWindow();
    }//GEN-LAST:event_optionBActionPerformed

    private void saveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBActionPerformed
        controller.save(getIdTF(), nameTF.getText(), scientificNameTF.getText());
    }//GEN-LAST:event_saveBActionPerformed

    private void addTagToThisFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTagToThisFoodActionPerformed
        String attribute = attributsList.get(allTags.getSelectedIndex()).toString();
        setFoodTags(attribute);
    }//GEN-LAST:event_addTagToThisFoodActionPerformed

    private void deleteTagsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTagsBActionPerformed
        try {
            foodTags.removeItemAt(foodTags.getSelectedIndex());
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_deleteTagsBActionPerformed

    private void editBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBActionPerformed
        controller.editFood();
    }//GEN-LAST:event_editBActionPerformed

    private void searchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBActionPerformed
        controller.searchFood(searchTF.getText());
    }//GEN-LAST:event_searchBActionPerformed

    private void addIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIconActionPerformed
        controller.addIcon();
    }//GEN-LAST:event_addIconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame mainFrame = new MainFrame();
                mainFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIcon;
    private javax.swing.JButton addTagToThisFood;
    private javax.swing.JList<String> allTags;
    private javax.swing.JButton deleteB;
    private javax.swing.JButton deleteTagsB;
    private javax.swing.JButton editB;
    private javax.swing.JComboBox<String> foodTags;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanelWithFoods;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton optionB;
    private javax.swing.JFrame optionFrame;
    private javax.swing.JButton saveB;
    private javax.swing.JTextField scientificNameTF;
    private javax.swing.JButton searchB;
    private javax.swing.JTextField searchTF;
    // End of variables declaration//GEN-END:variables

    /**
     * The method takes and adds tags.
     *
     * @param attribute Tags to add.
     */
    public void setFoodTags(String attribute) {
        for (int i = 0; i < foodTags.getItemCount(); i++) {
            if (foodTags.getItemAt(i).equals(attribute)) {
                return;
            }
        }
        foodTags.addItem(attribute);
    }

    /**
     *
     * @return Returns the list of tags of the selected food.
     */
    public JComboBox<String> getFoodTag() {
        return foodTags;
    }

    /**
     *
     * @return Return id number
     */
    public int getIdTF() {
        try {
            int id = Integer.parseInt(idTF.getText());
            return id;
        } catch (Exception ex) {
        }
        return -1;
    }

    /**
     * Sets the inscription in the id text box.
     *
     * @param string The inscription to be write into the id text box.
     */
    public void setIdTF(String string) {
        idTF.setText(string);
    }

    /**
     * Sets the inscription in the name text box.
     *
     * @param name The inscription to be write into the name text box.
     */
    public void setNameTF(String name) {
        nameTF.setText(name);
    }

    /**
     * Sets the inscription in the scientific name text box.
     *
     * @param string The inscription to be write in the scientific name text
     * box.
     */
    public void setScientificNameTF(String string) {
        scientificNameTF.setText(string);
    }

    /**
     *
     * @return Returns list of tags.
     */
    public DefaultListModel getAttributsList() {
        return attributsList;
    }

    /**
     *
     * @return Returns list of buttons with main window.
     */
    public List<JButton> getMainFrameButtons() {
        return mainFrameButtons;
    }

}
